name: CI/CD Frontend

on:
  push:
    branches:
      - deploy/andos-eextraits-front.0.0.1
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "Dockerfile,docker-compose.yml,nginx.conf,package.json,package-lock.json,vite.config.ts,src,public,index.html,eslint.config.js,postcss.config.js,tsconfig.app.json,tsconfig.json,tsconfig.node.json"
          target: "/root/andos_eextraits_front"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            TARGET_DIR="/root/andos_eextraits_front"

            if [ ! -d "$TARGET_DIR" ]; then
              echo "Error: Directory $TARGET_DIR does not exist."
              exit 1
            fi
            cd $TARGET_DIR
            
            echo "VITE_BASE_URL=http://andos-eextraits-back:8080" > .env
            echo "VITE_APP_NAME=AndOs eExtraits" >> .env
            echo "VITE_APP_NAME_MINI=eExtraits" >> .env
            
            docker-compose build andos-eextraits-front
            docker-compose -f docker-compose.yml up -d --force-recreate andos-eextraits-front
            docker image prune -f
            
            rm -rf Dockerfile docker-compose.yml nginx.conf package.json package-lock.json vite.config.ts src public index.html eslint.config.js postcss.config.js tsconfig.app.json tsconfig.json tsconfig.node.json