name: CI/CD Frontend

on:
  push:
    branches:
      - deploy/andos-eextraits-front.0.0.1
  workflow_dispatch:  # Permet de lancer le workflow manuellement depuis GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/andos-eextraits-front:latest
          build-args: |
            VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}

      - name: Copy deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "/root/andos_eextraits_front"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            TARGET_DIR="/root/andos_eextraits_front"

            if [ ! -d "$TARGET_DIR" ]; then
              echo "Error: Directory $TARGET_DIR does not exist."
              exit 1
            fi
            cd $TARGET_DIR

            IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/andos-eextraits-front:latest
            docker pull $IMAGE_TAG
            docker-compose up -d --force-recreate andos-eextraits-front
            docker image prune -f
            
            find . ! -name "." ! -name "docker-compose.yml" ! -name ".env" -exec rm -rf {} \;