name: CI/CD Frontend

on:
  push:
    branches:
      - deploy/andos-eextraits-front.0.0.1  # Déclenche le workflow à chaque push sur la branche 'main'
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: andos-eextraits-front
  DOCKER_REGISTRY: docker.io
  VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }} # Accède à la variable d'environnement sécurisée

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Utilise un runner Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/andos-eextraits-back:latest
          build-args: |
            VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push # Dépend du succès de l'étape de 'build_and_push'
    steps:
      - name: Pull and deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Changez de répertoire si nécessaire
            cd /root/andos_eextraits_front
            
            docker-compose build andos-eextraits-front
            docker-compose up -d --force-recreate andos-eextraits-front
            docker image prune -f